name: cgt
dependencies:
  - python==3.7
  - pip
  - pip:
    - dgl==0.4.3.post2
    - tqdm>=4.35.0
    - mlflow>=1.6.0
    - pandas>=0.24.2
    - matplotlib>=3.1.1
    - h5py>=2.9.0
    - sklearn
    - seaborn>=0.9.0
    - histocartography==0.2.0
    - torch==1.9.1+cu111 torchaudio -f https://download.pytorch.org/whl/cu111/torch_stable.html
    - torch-scatter -f https://pytorch-geometric.com/whl/torch-1.9.1+cu111.html
    - torch-sparse -f https://pytorch-geometric.com/whl/torch-1.9.1+cu111.html